### ISSUE TITLE
Write a 60-second pitch of our product

### ISSUE THREAD

**Issue by rramphal100** [rramphal100/purehouse#31]
Everyone should try to make a 60-second pitch of NewHaus. This is good for our presentation and good for making us learn what we do not fully understand about our product right now.

Let's ask each other questions we have when doing this! It will make us much better at marketing our product.

**Comment by annaguidi** [comment]
are we submitting this on that how Did I do? (from guy in studio skills)

**Comment by twd38** [comment]
We can do that

**Comment by annaguidi** [comment]
great, I think we should!
